/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  canaryCheckerSidebar: [
    {
      type: 'doc',
      id: 'canary-checker/health-checks',
      label: 'Overview'
    },
    {
      type: 'doc',
      id: 'canary-checker/getting-started',
      label: 'Getting Started'
    },
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'generated-index',
        title: 'Installation',
        slug: '/canary-checker/installation'
      },
      items: [
        {
          type: 'doc',
          id: 'canary-checker/cli',
          label: 'CLI'
        },

      ]
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'doc',
          id: 'canary-checker/concepts/metrics-exporter',
          label: 'Metrics Exporter'
        },
        {
          type: 'doc',
          id: 'canary-checker/concepts/grafana',
          label: 'Grafana'
        },

        {
          type: 'category',
          label: 'Expressions',
          link: {
            type: 'generated-index',
            title: 'Expressions',
            slug: '/canary-checker/concepts/expressions'
          },
          items: [
            {
              type: 'doc',
              id: 'canary-checker/concepts/display-formatting',
              label: 'Display Formatting'
            },
            {
              type: 'doc',
              id: 'canary-checker/concepts/health-evaluation',
              label: 'Health Evaluation'
            },

            {
              type: 'doc',
              id: 'canary-checker/concepts/transforms',
              label: 'Transforms'
            }
          ]
        },

        {
          type: 'doc',
          id: 'canary-checker/concepts/troubleshooting',
          label: 'Troubleshooting'
        }
      ]
    },

    {
      type: 'html',
      value: '<span class="font-semibold" >Common Checks</span>',
      defaultStyle: true
    },
    {
      type: 'doc',
      id: 'canary-checker/reference/http',
      label: 'HTTP'
    },


    {
      type: 'doc',
      id: 'canary-checker/reference/prometheus',
      label: 'Prometheus'
    },

    {
      type: 'doc',
      id: 'canary-checker/reference/kubernetes',
      label: 'Kubernetes Resources'
    },

    {
      type: 'doc',
      id: 'canary-checker/reference/pod',
      label: 'Pod'
    },

    {
      type: 'doc',
      id: 'canary-checker/reference/exec',
      label: 'Exec'
    },
    {
      type: 'doc',
      id: 'canary-checker/reference/folder',
      label: 'Folder'
    },

    {
      type: 'doc',
      id: 'canary-checker/reference/sql',
      label: 'SQL'
    },


    {
      type: 'category',
      label: 'Other Checks',
      className: "condensed",
      collapsed: false,
      items: [

        {
          type: 'html',
          value: '<span class="font-semibold" >Protocols</span>',

          defaultStyle: true
        },

        {
          type: 'doc',
          id: 'canary-checker/reference/dns',
          label: 'DNS',
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/icmp',
          label: 'ICMP'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/tcp',
          label: 'TCP'
        },


        {
          type: 'doc',
          id: 'canary-checker/reference/s3-protocol',
          label: 'S3 Protocol'
        },

        {
          type: 'html',
          value: '<span class="font-semibold" >Alerts</span>',
          defaultStyle: true
        },

        {
          type: 'doc',
          id: 'canary-checker/reference/alert-manager',
          label: 'Alert Manager'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/cloudwatch',
          label: 'AWS Cloud Watch'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/aws-config-rule',
          label: 'AWS Config Rule'
        },


        {
          type: 'html',
          value: '<span class="font-semibold" >Data Sources</span>',
          defaultStyle: true
        },

        {
          type: 'doc',
          id: 'canary-checker/reference/aws-config',
          label: 'AWS Config'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/configdb',
          label: 'Flanksource Config DB'
        },

        {
          type: 'doc',
          id: 'canary-checker/reference/elasticsearch',
          label: 'Elasticsearch'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/ldap',
          label: 'LDAP'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/mongo',
          label: 'MongoDB'
        },

        {
          type: 'doc',
          id: 'canary-checker/reference/redis',
          label: 'Redis'
        },

        {
          type: 'html',
          value: '<span class="font-semibold" >Infrastructure</span>',
          defaultStyle: true
        },

        {
          type: 'doc',
          id: 'canary-checker/reference/containerd',
          label: 'Containerd/Docker'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/helm',
          label: 'Helm'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/ec2',
          label: 'EC2'
        },

        {
          type: 'html',
          value: '<span class="font-semibold" >Integration</span>',
          defaultStyle: true
        },


        {
          type: 'doc',
          id: 'canary-checker/reference/jmeter',
          label: 'JMeter'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/junit',
          label: 'JUnit'
        },

        {
          type: 'doc',
          id: 'canary-checker/reference/azure-devops',
          label: 'Azure DevOps'
        },

        {
          type: 'doc',
          id: 'canary-checker/reference/k6',
          label: 'K6'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/newman',
          label: 'Newman / Postman'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/playwright',
          label: 'Playwright'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/gcs-database-backup',
          label: 'GCS Database Backup'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/restic',
          label: 'Restic'
        }
      ]
    },
    {
      type: 'category',
      label: 'Comparisons',
      items: [
        {
          type: 'doc',
          id: 'canary-checker/comparisons/blackbox-exporter',
          label: 'Blackbox Exporter'
        }
      ]
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'doc',
          id: 'canary-checker/concepts/image-variants',
          label: 'Image Variants'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/canary-spec',
          label: 'Canary Spec'
        },
        {
          type: 'doc',
          id: 'canary-checker/reference/connections',
          label: 'Cloud Connections'
        }
      ]
    }
  ],
  configdbSidebar: [
    {
      type: 'doc',
      id: 'config-db/overview',
      label: 'Overview'
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'doc',
          id: 'config-db/concepts/relationships',
          label: 'Relationships'
        },
        {
          type: 'doc',
          id: 'config-db/concepts/transform',
          label: 'Transformation'
        },
        {
          type: 'doc',
          id: 'config-db/concepts/retention',
          label: 'Retention'
        },
        {
          type: 'doc',
          id: 'config-db/concepts/changes',
          label: 'Changes'
        },

        {
          type: 'doc',
          id: 'config-db/concepts/insights',
          label: 'Insights'
        },


      ]
    },
    {
      type: 'category',
      label: 'Scrapers',
      items: [
        {
          type: 'doc',
          id: 'config-db/scrapers/aws',
          label: 'AWS'
        },
        {
          type: 'doc',
          id: 'config-db/scrapers/azure',
          label: 'Azure'
        },
        {
          type: 'doc',
          id: 'config-db/scrapers/azure-devops',
          label: 'Azure DevOps'
        },

        {
          type: 'doc',
          id: 'config-db/scrapers/github',
          label: 'Github'
        },
        {
          type: 'doc',
          id: 'config-db/scrapers/trivy',
          label: 'Trivy'
        },
        {
          type: 'doc',
          id: 'config-db/scrapers/kubernetes',
          label: 'Kubernetes'
        },
        {
          type: 'category',
          label: 'Custom',
          items: [
            {
              type: 'doc',
              id: 'config-db/concepts/custom-scrapers',
              label: 'Overview'
            },
            {
              type: 'doc',
              id: 'config-db/scrapers/file',
              label: 'File'
            },
            {
              type: 'doc',
              id: 'config-db/scrapers/kubernetes-file',
              label: 'Kubernetes File'
            },
            {
              type: 'doc',
              id: 'config-db/scrapers/sql',
              label: 'SQL'
            }]
        },
      ]
    },

    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'doc',
          id: 'config-db/tutorials/file-scraper',
          label: 'Scraping Custom File'
        },
        {
          type: 'doc',
          id: 'config-db/tutorials/date-mapping',
          label: 'Extracting config creation/deletion dates'
        },
      ]
    }
  ],
  playbooksSidebar: [

    {
      type: 'autogenerated',
      dirName: 'playbooks'

    },

  ],
  topologySidebar: [
    {
      type: 'doc',
      id: 'topology/overview',
      label: 'Overview'
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'doc',
          id: 'topology/concepts/properties',
          label: 'Properties'
        },
        {
          type: 'doc',
          id: 'topology/concepts/lookup',
          label: 'Lookup'
        },
        {
          type: 'doc',
          id: 'topology/concepts/catalog',
          label: 'Catalog'
        },
        {
          type: 'doc',
          id: 'topology/concepts/health-checks',
          label: 'Health Checks'
        },
        {
          type: 'doc',
          id: 'topology/concepts/templating',
          label: 'Templating'
        }
      ]
    },


    {
      type: 'category',
      label: 'Lookups',
      link: {
        type: 'generated-index',
        title: 'Component Lookup',
        slug: 'topology/references/lookup'
      },
      items: [
        {
          type: 'doc',
          id: 'topology/references/configdb',
          label: 'Catalog'
        },
        {
          type: 'doc',
          id: 'topology/references/exec',
          label: 'Exec'
        },
        {
          type: 'doc',
          id: 'topology/references/http',
          label: 'HTTP'
        },
        {
          type: 'doc',
          id: 'topology/references/kubernetes',
          label: 'Kubernetes'
        },
        // Mongo lookup cannot query
        // {
        //   type: 'doc',
        //   id: 'topology/references/mongo',
        //   label: 'Mongo'
        // },
        {
          type: 'doc',
          id: 'topology/references/sql',
          label: 'SQL'
        },
        {
          type: 'doc',
          id: 'topology/references/prometheus',
          label: 'Prometheus'
        }
        // Redis component lookup isn't implemeneted. You can't supply a query.
        // {
        //   type: 'doc',
        //   id: 'topology/references/redis',
        //   label: 'Redis'
        // }
      ]
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        {
          type: 'doc',
          id: 'topology/examples/embedding',
          label: 'Embedding Cards'
        },
        {
          type: 'doc',
          id: 'topology/examples/prometheus',
          label: 'Prometheus'
        },
        {
          type: 'doc',
          id: 'topology/examples/flux',
          label: 'Flux'
        },
        {
          type: 'doc',
          id: 'topology/examples/kubernetes',
          label: 'Kubernetes'
        },
        {
          type: 'doc',
          id: 'topology/examples/kubernetes-workload',
          label: 'Kubernetes-workload'
        }
      ]
    }
  ],
  notificationsSidebar: [
    {
      type: 'doc',
      id: 'notifications/overview',
      label: 'Overview'
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'doc',
          id: 'notifications/concepts/filtering',
          label: 'Filtering'
        },
        {
          type: 'doc',
          id: 'notifications/concepts/templating',
          label: 'Templating'
        }
      ]
    },
    {
      type: 'category',
      label: 'Events',
      link: {
        type: 'generated-index',
        title: 'Notification Events',
        slug: '/notifications/events'
      },
      items: [
        {
          type: 'doc',
          id: 'notifications/events/components',
          label: 'Components'
        },
        {
          type: 'doc',
          id: 'notifications/events/health-checks',
          label: 'Health Checks'
        },
        {
          type: 'doc',
          id: 'notifications/events/incidents',
          label: 'Incidents'
        }
      ]
    },
    {
      type: 'doc',
      id: 'notifications/channels',
      label: 'Channels'
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        {
          type: 'doc',
          id: 'notifications/examples/slack',
          label: 'Slack'
        }
      ]
    }
  ],
  registrySidebar: [
    {
      type: 'doc',
      id: 'registry/overview',
      label: 'Overview'
    },
    {
      type: 'doc',
      id: 'registry/aws',
      label: 'AWS'
    },
    {
      type: 'doc',
      id: 'registry/kubernetes',
      label: 'Kubernetes'
    }
  ],
  reference: [
    {
      type: 'doc',
      id: 'reference/env-var',
      label: 'Env Vars'
    },

    {
      type: 'category',
      label: 'Connections',
      items: [
        {
          type: 'doc',
          id: 'reference/connection',
          label: 'Overview'
        },
        {
          type: 'doc',
          id: 'reference/connections/aws',
          label: 'AWS'
        },
        {
          type: 'doc',
          id: 'reference/connections/gcp',
          label: 'GCP'
        },
        {
          type: 'doc',
          id: 'reference/connections/azure',
          label: 'Azure'
        }
      ]
    },



    {
      type: 'doc',
      id: 'reference/resource-selector',
      label: 'Resource Selectors'
    },

    {
      type: 'category',
      label: 'Catalog',
      items: [
        {
          type: 'doc',
          id: 'reference/config-db/config-item',
          label: 'Config Item'
        },
        {
          type: 'doc',
          id: 'reference/config-db/scrape-result',
          label: 'Scrape Result'
        },
        {
          type: 'doc',
          id: 'reference/config-db/changes',
          label: 'Changes'
        }
      ]
    },

    {
      type: 'category',
      label: 'Health Checks',
      items: [
        {
          type: 'doc',
          id: 'reference/canary-checker/check',
          label: 'Check'
        }
      ]
    },

    {
      type: 'category',
      label: 'Playbooks',
      items: [
        {
          type: 'doc',
          id: 'reference/playbooks/playbook',
          label: 'Playbook'
        },
        {
          type: 'doc',
          id: 'reference/playbooks/parameters',
          label: 'Parameters'
        },
        {
          type: 'doc',
          id: 'reference/playbooks/webhooks',
          label: 'Webhooks'
        },
        {
          type: 'doc',
          id: 'reference/playbooks/events',
          label: 'Events'
        },

        {
          type: 'doc',
          id: 'reference/playbooks/context',
          label: 'Context'
        },


      ]
    },

    {
      type: 'category',
      label: 'Topology',
      items: [
        {
          type: 'doc',
          id: 'topology/references/topology',
          label: 'Topology'
        },
        {
          type: 'doc',
          id: 'topology/references/components',
          label: 'Components'
        },
        {
          type: 'doc',
          id: 'reference/property',
          label: 'Properties'
        },
      ]
    },
    {
      type: 'doc',
      label: 'Common Types',
      id: 'reference/types',
    },
    {
      type: 'category',
      label: 'Scripting',
      link: {
        type: 'generated-index',
        title: 'Scripting',
        slug: '/reference/scripting'
      },
      items: [
        {
          type: 'doc',
          id: 'reference/scripting/gotemplate',
          label: 'Go Templates'
        },
        {
          type: 'doc',
          id: 'reference/scripting/cel',
          label: 'CEL Expressions'
        },
        {
          type: 'doc',
          id: 'reference/scripting/javascript',
          label: 'Javascript'
        }
      ]
    }
  ],
  overview: [
    {
      type: 'doc',
      id: 'index',
      label: 'Overview'
    },
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'generated-index',
        title: 'Installation',
        slug: '/installation'
      },
      items: [
        {
          type: 'doc',
          label: 'SaaS',
          id: 'installation/saas'
        },

        {
          type: 'category',
          label: 'Self-Hosted',
          items: [
            {
              type: 'doc',
              id: 'installation/helm',
              label: 'Helm'
            },
            {
              type: 'doc',
              id: 'installation/database',
              label: 'Database'
            },
            {
              type: 'doc',
              id: 'installation/oidc',
              label: 'SSO (OIDC)'
            },
            {
              type: 'doc',
              id: 'installation/monitoring-and-tracing',
              label: 'Monitoring & Tracing'
            },
            // {
            //   type: 'doc',
            //   id: 'installation/artifacts',
            //   label: 'Artifacts'
            // },
          ]
        },

        {
          type: 'category',
          label: 'Cloud Providers',
          items: [
            {
              type: 'doc',
              id: 'installation/aws-eks',
              label: 'AWS EKS'
            }
          ]
        },

        {
          type: 'category',
          label: 'Local Testing',
          items: [
            {
              type: 'doc',
              id: 'installation/kind_linux',
              label: 'Kind'
            },
            {
              type: 'doc',
              id: 'installation/minikube_windows',
              label: 'Minikube (Windows)'
            }
          ]
        }
      ]
    },

    {
      type: 'doc',
      id: 'architecture',
      label: 'Architecture'
    },
    {
      type: 'doc',
      id: 'security',
      label: 'Security'
    }
  ]
}

module.exports = sidebars
