apiVersion: v1
kind: Namespace
metadata:
  name: control-plane-tests
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: control-plane-tests
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: control-plane-tests
      version: "*"
  interval: 1h
  values:
    auth:
      database: my_database
      password: qwerty123
      username: admin
    primary:
      persistence:
        enabled: true
        size: 8Gi
