apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: control-plane-tests
  namespace: control-plane-tests
spec:
  # how often to run the test
  schedule: "@every 1h"
  //highlight-next-line
  kubernetesResource: # this is type of canary we are executing, canary-checker has many more
    - name: helm-release-postgres-check
      waitFor:
        # The time to wait for the resources to be ready before considering the test a failure
        timeout: 10m
      staticResources:
        //highlight-next-line
        - # A list of resources that should be created once only and re-used across multiple tests
      resources:
        //highlight-next-line
        - # A list of resources to be created every time the check runs
      display:
        # optional Go text template to display the results of the check
        template: |+
          Helm release created: {{ .health | toYAML  }}
