module.exports = {
  docs: [

    {
      type: 'autogenerated',
      dirName: "."
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: true,
      items: [
        {
          type: 'link',
          href: 'https://flanksource.com/docs/blog/infrastructure-testing-with-canary-checker-and-flux',
          label: 'Synthetic Testing with Flux and Helm'
        }
      ]

    },


  ]
}
