module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'health-checks',
      label: 'Overview'
    },
    {
      type: 'doc',
      id: 'getting-started.canary',
      label: 'Getting Started'
    },
    {
      type: 'category',
      label: "Installation",
      items: [
        {
          label: "Helm",
          type: "doc",
          id: "installation/helm.canary"
        },
        {
          label: "CLI",
          type: "doc",
          id: "installation/cli"
        },

        {
          label: "Database",
          type: "doc",
          id: "installation/database.canary"
        },

        {
          label: "Image Variants",
          type: 'doc',
          id: 'installation/image-variants'
        },
      ]
    },
    {
      type: 'category',
      label: "Concepts",
      items: [{
        type: 'autogenerated',
        dirName: "concepts"
      }]

    },
    {
      type: 'category',
      label: 'Checks',
      link: { type: 'doc', id: 'reference/category' },
      items: [
        {
          className: 'condensed',
          type: 'autogenerated',
          dirName: 'reference'
        }
      ]
    },

    {
      type: 'category',
      label: 'Examples',

      items: [

        {
          className: 'condensed',
          type: 'autogenerated',
          dirName: 'examples',

        }
      ]
    },

    {
      type: 'category',
      label: 'Scripting',
      items: [

        {
          label: "CEL",
          type: 'doc',
          id: 'scripting/cel'
        },
        {
          label: "Go Templates",
          type: 'doc',
          id: 'scripting/gotemplate'
        },
        {
          label: "Javascript",
          type: 'doc',
          id: 'scripting/javascript'
        },

        {
          label: "Common Types",
          type: 'doc',
          id: 'types'
        },


      ]
    },
    {
      type: 'category',
      label: 'Comparisons',
      items: [
        {
          type: 'doc',
          id: 'comparisons/blackbox-exporter',
          label: 'Blackbox Exporter'
        }
      ]
    },
    {
      type: 'doc',
      id: 'troubleshooting',
      label: 'Troubleshooting'
    },


    {
      type: 'category',
      label: 'Tutorials',
      collapsed: true,
      items: [
        {
          type: 'link',
          href: 'https://flanksource.com/docs/blog/infrastructure-testing-with-canary-checker-and-flux',
          label: 'Synthetic Testing with Flux and Helm'
        }
      ]

    },


  ]
}
