apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: http-check
spec:
  interval: 30
  http:
    - name: basic-check
      url: https://httpbin.demo.aws.flanksource.com/status/200
    - name: failing-check
      url: https://httpbin.demo.aws.flanksource.com/status/500
