apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: http-check
spec:
  http:
    - name: USD
      url: https://api.frankfurter.app/latest?from=USD&to=GBP,EUR,ILS
      display:
        javascript: |
          currencyCodes = {
            "EUR": "€",
            "GBP": "£",
            "ILS": "₪"
          }
          console.log(JSON.stringify(json.rates))

          display = ""
          for (var currency in json.rates) {
            if (display != "") {
              display += ", "
            }
            display += currency + " = " + currencyCodes[currency] + json.rates[currency] + ", "
          }
          "$1 = " + display
