apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: http
spec:
  interval: 30
  http:
    - name: http-minimal-check
      url: https://httpbin.demo.aws.flanksource.com/status/200
      metrics:
        - name: httpbin_2xx_count
          type: counter
          value: "{{if eq .result.code 200 }}1{{else}}0{{end}}"
          labels:
            name: httpbin_2xx_count
            check_name: "{{ .check.name }}"
            statusClass: "2xx"
